### ISSUE TITLE
Ruby container won't start

### ISSUE THREAD

**Issue by albertski** [wodby/docker4ruby#3]
Noticing that my ruby container won't start.  It just shows exit code 127.
  
### Host OS 

macOS Catolina

### Docker info output
```
# Run "docker info" on the host machine and paste output here 
```

### Docker compose file
```yml
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  ruby:
    build:
      context: ./
      args:
        RUBY_TAG: $RUBY_TAG
    container_name: "${PROJECT_NAME}_ruby"
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_ADAPTER: $DB_ADAPTER
    volumes:
      - ./:/usr/src/app:cached
## For macOS users (https://wodby.com/docs/stacks/ruby/local#docker-for-mac)
#      - ./:/usr/src/app:cached # User-guided caching
#      - docker-sync:/usr/src/app # Docker-sync

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: ruby
      NGINX_VHOST_PRESET: http-proxy
    volumes:
      - ./:/usr/src/app
# Options for macOS users (https://wodby.com/docs/stacks/ruby/local#docker-for-mac)
#      - ./:/usr/src/app:cached # User-guided caching
#      - docker-sync:/usr/src/app # Docker-sync
    labels:
      - 'traefik.backend=${PROJECT_NAME}_nginx_1'
      - 'traefik.entrypoint=http'
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.priority=10'
      - 'traefik.frontend.rule=Host:${PROJECT_NAME}.test'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - 'traefik.backend=${PROJECT_NAME}_mailhog_1'
    - 'traefik.port=8025'
    - 'traefik.frontend.rule=Host:mailhog.${PROJECT_NAME}.test'
```

### Logs output
I see the message exit code 127 when it tries to start it.  This is the logs in Portainer:

```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
/docker-entrypoint.sh: line 62: exec: puma: not found
```

Gem file has  `gem 'puma', '~> 4.1'`
